### ISSUE TITLE
The "Put a closure on it" section is very poor

### ISSUE THREAD

**Issue by domenic** [max-mapper/callback-hell#10]
First, the section has nothing to do with closures, at all. No variables are being closed over. It is maybe an example of factory functions, if anything.

Second, it has nothing to do with the rest of the page, and callback hell in general. It's more about someone's favorite pattern for decoupling DOM events from "business logic."

Finally, at the end it's trying to advertise hootroot.com, whatever that is.

IMO it doesn't belong on callbackhell.com.

**Comment by max-mapper** [comment]
you raise some valid points, perhaps i should break it out and link to it as an additional resource
