### ISSUE TITLE
Promises

### ISSUE THREAD

**Issue by igorw** [max-mapper/callback-hell#12]
The ultimate solution to all of your callback troubles. Sample implementation: [when.js](https://github.com/cujojs/when).

**Comment by max-mapper** [comment]
promises are too heavy for the problems they solve. 90% callbacks are fine. in the situations when you need callback aggregation there are tons of little libraries you can use like what you linked

**Comment by igorw** [comment]
The only thing that really disturbs me about this reaction is the fact that you run a website that helps deal with async control flow, yet refuse to list valid approaches because of your personal disagreement with them.

**Comment by max-mapper** [comment]
It's called curation. The scope of the site is based on the experience of myself and others mostly in the node community where simplicity is favored and code that uses promises is usually overengineered. 

I wouldn't be opposed to a section about libraries that are useful for dealing with complex flow control problems but when you open with "the answer to all your problems..."  you are inviting an opinionated response.

**Comment by igorw** [comment]
Let me fix my previous statement then.

> Yet refuse to list valid approaches because of your personal disagreement with me.
