### ISSUE TITLE
So why anonymous functions?

### ISSUE THREAD

**Issue by cawoodm** [max-mapper/callback-hell#14]
I sorta slept through web2.0 and when I got back into it EVERYONE was doing what Max calls callback hell so so did I. But it's more than just callback hell it's `insane nesting`. At the top you typically have a (function(){...}()) and everything inside ... is nested to the 27th degree. It's so easy to get confused about where a } or ; or , belongs that it can really waste your time compared to named functions.

I get it about keeping code out of the global namespace. I can also see some benefit in IDEs which collapse the various sections but are there any other reasons? _Why did the JS developer community start using anonymous functions and "infinite" nesting?_

**Comment by max-mapper** [comment]
good question. I think the lazy thing to do is to nest but it comes back to haunt you if you use it too much. naming functions is a good idea, so is keeping your code flat (not insanely nested). these are good points that i'll try to incorporate into the flow of callbackhell in the future. thanks!
